### ISSUE TITLE
Public availability

### ISSUE THREAD

**Issue by IzzySoft** [DanielBerge/notification-notes#2]
First thanks for keeping your app tracker-free and privacy-friendly!

Have you ever considered making it publicly available – I mean, outside the walled gardens, so folks without access to Play (or Apple) can use it? You could e.g. [tag your releases](https://github.com/DanielBerge/notification-notes/releases) and attach the APK there. Or bring your app to [F-Droid](https://f-droid.org/).

**Comment by DanielBerge** [comment]
Thank you for your feedback, i added a new tagged release under [releases](https://github.com/DanielBerge/notification-notes/releases) with the newest APK. Will do this in the future too :+1:

**Comment by IzzySoft** [comment]
Cool, thanks! It will then become available [in my repo](https://apt.izzysoft.de/fdroid/index/apk/no.berge.notificationnotes) with the next sync tomorrow around 7 pm UTC. You are welcome to use [these badges](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there, e.g. from the Readme.

Btw: It would be great if the tag name and the `versionName` would be in sync (with future releases). Currently, the tag says "2.0.2" while the APK says "2.0.15" :wink: My updater runs once per day and looks for newer tags. Once such exists with an APK attached, it will be fetched and updated in my repo automatically. Any [F-Droid Client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) can be used on-device for this purpose, and no registration is needed.

Should you want to proceed to F-Droid itself (your app would then be built from source by F-Droid – which gives the user the guarantee the APK is really based on the specified code without any "additions") and signed with an F-Droid specific key (reproducible builds are possible if you wish, and would then be dual-signed).

So thanks again, and all the best wishes!
